version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongo

  frontend:
    build:
      context: ./fronted
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
    volumes:
      - ./fronted:/usr/src/app
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
