apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode5-deployment
  labels:
    app: episode5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: episode5
  template:
    metadata:
      labels:
        app: episode5
    spec:
      containers:
      - name: frontend
        image: khadijahmehmood/frontendep5:latest
        ports:
        - containerPort: 5004
      - name: backend
        image: khadijahmehmood/backendep5:latest
        ports:
        - containerPort: 3004